//! Typed role facades over the internal archive engine.
//!
//! [`ArchiveReader`] (listing/reading/verification), [`ArchiveWriter`]
//! (create/append) and [`ArchiveEditor`] (delete/rename/comment/recovery)
//! are the supported public API (ADR 0006); they share the `RarArchive`
//! engine defined here together with the archive state, entry-point
//! constructors and drop-time cleanup.
//!
//! This module is intentionally a thin seam. Read/decode lives in
//! `crate::format::rar5::extract` and `crate::format::rar4`, the write
//! pipeline in `crate::format::shared` + `crate::format::{rar5,rar4}::write`,
//! create/append finalization in `crate::archive::create`, and surgical
//! edit transactions (delete/rename/comment/recovery) in
//! `crate::archive::transaction`.

mod create;
mod ctx;
mod editor;
mod engine;
mod ops;
pub(crate) mod rar4_edit;
mod reader;
mod reconstruct;
mod rename;
mod transaction;
mod writer;

#[cfg(test)]
mod test_support;
#[cfg(test)]
mod tests;

use std::fs::File;
use std::io::{Seek, SeekFrom, Write};
use std::path::{Path, PathBuf};

use crate::crypto;
use crate::crypto::ENCR_IV_SIZE;
use crate::error::{RarError, RarResult};
use crate::format::rar5::headers::{
    BlockCursor, main_header_locator_fields, parse_service_block_name,
    parse_service_recovery_percent, split_main_extra,
};
use crate::format::rar5::{
    ARCHIVE_FLAG_LOCKED, BLOCK_FLAG_EXTRA_DATA, BLOCK_TYPE_END_ARCHIVE, BLOCK_TYPE_FILE_HEADER,
    BLOCK_TYPE_SERVICE_HEADER,
};
use crate::fs::atomic::{copy_prefix, install_durable, read_write_create, temp_sibling_path};
use crate::vint;
use crate::write_progress::ProgressTracker;

use crate::engine::{
    CompressionSettings, LocatorState, MetadataSettings, OutputState, Rar4Append, ReadState,
    SolidChain, WriteState,
};
// Re-exported for this module's children, which reach them as `super::X`.
pub(crate) use crate::engine::{
    ArchiveStream, DecryptedPayload, Mode, PendingCommit, StreamRecord, cancel_requested,
};

pub use crate::engine::discover_volumes;
pub use crate::engine::{ArchiveEntry, BatchEntry};
pub use crate::format::shared::extract::ExtractionReport;
pub(crate) use crate::fs::volume::{
    volume_base_of, volume_path, volume_path_padded, volume_path_rar4,
};
pub use editor::{ArchiveEditor, EditOp, EditPlan, EditReport};
pub use reader::{
    ArchiveReader, Entries, EntryId, EntryMatches, EntryRef, OpenOptions, ScanStrategy,
    VerificationFailure, VerificationReport,
};
pub use reconstruct::{ReconstructReport, reconstruct_archive_path};
pub use writer::{
    AppendOptions, ArchiveWriter, CompressionLevel, EntryWriteOptions, SolidMode, ThreadCount,
    WriteEntry, WriteReport, WriterOptions,
};

// Inline RAR5 recovery records are generated by streaming the archive prefix
// from disk (see `rar50::build_structural_inline_recovery_data_streaming`), so
// they are no longer bounded by an in-RAM prefix buffer and can be added to
// arbitrarily large archives.

/// Legacy RAR archive engine: the shared implementation behind
/// [`ArchiveReader`], [`ArchiveWriter`] and [`ArchiveEditor`].
///
/// Crate-internal (ADR 0006): the public surface is the typed role facades
/// only. This module is private, so the type is unreachable from outside even
/// though it stays `pub` for in-crate tests and the facade delegation.
pub struct RarArchive {
    pub(crate) path: PathBuf,
    pub(crate) mode: Mode,
    /// Set before the first trailing write of `RarArchive::finish_writing`.
    /// Once finalization has been attempted, a failed/partial result must
    /// never be finalized again (a retry could append a second quick-open /
    /// recovery record or patch the wrong offset): `RarArchive::close` and
    /// [`Drop`] both refuse to re-enter it.
    pub(crate) finalize_started: bool,
    pub(crate) entries: Vec<ArchiveEntry>,
    /// The archive stream: a file, or any caller-provided seekable
    /// read/write sink (in-memory `Cursor` in tests, stdin/stdout for
    /// future `-si` support).
    pub(crate) stream: Option<Box<dyn ArchiveStream>>,
    /// Byte offset where the RAR5 signature begins (0 for plain archives,
    /// >0 for SFX archives whose stub precedes the archive).
    pub(crate) sfx_offset: u64,
    /// The container family the archive belongs to (read) or is being
    /// written as (write).
    pub(crate) family: crate::detect::ArchiveFamily,
    /// The archive is solid at the container level: legacy `MHD_SOLID`
    /// (pre-RAR3 codecs chain by that flag + position, since they never
    /// write the per-file FHD_SOLID bit), RAR13 `MHD_SOLID`, or RAR5's
    /// `ARCHIVE_FLAG_SOLID`.
    pub(crate) archive_solid: bool,
    /// Password for encrypted archives.
    pub(crate) password: Option<String>,
    /// Encrypt archive headers (file names/structure hidden) — RAR5
    /// archive-level encryption header + AES-256-CBC per-block headers.
    pub(crate) header_encryption: bool,
    /// Archive-level encryption parameters when header encryption is on.
    pub(crate) archive_encr: Option<crypto::EncryptionParams>,
    /// The header-encryption AES key, derived once and reused for every
    /// block header of the archive (and each of its volumes).
    pub(crate) archive_keys: Option<crypto::DerivedKeys>,
    /// Recovery record: recovery percent (0-100) when the archive is created
    /// with an inline RAR5 recovery record ("RR" service header).
    pub(crate) recovery_percent: Option<u8>,
    /// Recovery volumes: percent (0-100) of `.rev` files created alongside
    /// a multi-volume archive (WinRAR `-rv`).
    pub(crate) recovery_volumes_percent: Option<u8>,
    /// Recovery volumes: exact `.rev` file count (auto-capped at the data
    /// volume count).
    pub(crate) recovery_volumes_count: Option<u32>,
    /// All volume file paths (multi-volume archives).
    pub(crate) volume_paths: Vec<PathBuf>,
    /// Optional progress callback invoked during compression. Since the
    /// `parallel` feature compresses waves of members concurrently, the
    /// tracker behind this field aggregates every member's deltas into one
    /// monotonic stream; the callback observes `(committed, total)` where
    /// `total` is the whole write operation's input byte count. See
    /// [`write_progress::ProgressTracker`].
    pub(crate) progress:
        Option<std::sync::Arc<std::sync::Mutex<crate::write_progress::ProgressTracker>>>,
    /// Index (into the current batch) of the member being written. Set by
    /// `add_batch` before each sequential member so its per-member progress
    /// is routed to the right tracker slot.
    pub(crate) progress_member: usize,
    /// Caller-owned cancellation flag: when set to true, long-running
    /// create/extract/repair operations abort at their next check point
    /// with [`crate::RarError::Cancelled`]. Installed with
    /// [`Self::set_cancel_flag`]; `None` = never cancelled.
    pub(crate) cancel: Option<std::sync::Arc<std::sync::atomic::AtomicBool>>,
    /// Read-side state (solid decode, extract options, NTFS streams).
    /// Present when the archive is opened for reading or appending.
    pub(crate) read: Option<ReadState>,
    /// Write-side state (solid mode, compression, quick-open, recovery).
    /// Present when the archive is opened for writing or appending.
    pub(crate) write: Option<WriteState>,
}

/// A seekable read/write sink for archive streams: `File` in production,
/// `Cursor<Vec<u8>>` for in-memory archives (tests, future `-si` support).
impl RarArchive {
    // ── Constructors ───────────────────────────────────────────────────────

    /// Build a default `RarArchive` shell for a given mode and password.
    /// Every field is at its zero/default; the caller must call the
    /// appropriate open/prepare method afterward.
    fn new_for_mode(path: PathBuf, mode: Mode, password: Option<String>) -> Self {
        let (read, write) = match mode {
            Mode::Read => (Some(ReadState::default()), None),
            Mode::Write => (None, Some(WriteState::default())),
            Mode::Append => (Some(ReadState::default()), Some(WriteState::default())),
        };
        RarArchive {
            path,
            mode,
            finalize_started: false,
            entries: Vec::new(),
            sfx_offset: 0,
            family: crate::detect::ArchiveFamily::Rar50Plus,
            archive_solid: false,
            stream: None,
            password,
            header_encryption: false,
            archive_encr: None,
            archive_keys: None,
            recovery_percent: None,
            recovery_volumes_percent: None,
            recovery_volumes_count: None,
            volume_paths: Vec::new(),
            progress: None,
            progress_member: 0,
            cancel: None,
            read,
            write,
        }
    }

    /// Install a cancellation flag. The flag is an `Arc<AtomicBool>` the
    /// caller owns: set it to `true` from any thread and the current
    /// create / append / extract / read / repair operation returns
    /// [`crate::RarError::Cancelled`] at its next per-member or per-chunk
    /// check point (at most one chunk or member later). Pass `None` to
    /// disable cancellation.
    ///
    /// The binding layer uses this to honor an `AbortSignal`: wrap the
    /// signal in a shared flag before starting the `AsyncTask`.
    pub fn set_cancel_flag(&mut self, flag: Option<std::sync::Arc<std::sync::atomic::AtomicBool>>) {
        self.cancel = flag;
    }

    /// Set the compression thread count for this archive (like `-mt<N>`),
    /// overriding the process-global default. `Some(0)` requests automatic
    /// sizing for this archive; `None` restores the global default. The pool
    /// is chosen per thread count, so concurrent archives with different
    /// settings each run on their own pool and never interfere. Requires the
    /// `parallel` feature; without it compression stays sequential.
    pub fn set_compression_threads(&mut self, threads: Option<usize>) -> RarResult<()> {
        if self.mode == Mode::Read {
            return Err(RarError::InvalidState(
                "compression threads can only be set while writing or appending".into(),
            ));
        }
        crate::options::validate_threads(threads)?;
        let write = self
            .write
            .as_mut()
            .ok_or_else(|| RarError::InvalidState("write context is not available".into()))?;
        write.compression.threads = threads;
        Ok(())
    }

    /// Forget the archive-level encryption state, so a re-read starts from
    /// the plaintext leading encryption header.
    pub(crate) fn clear_archive_encryption(&mut self) {
        self.header_encryption = false;
        self.archive_encr = None;
        self.archive_keys = None;
    }

    /// The header-encryption AES key: the cached derivation when present,
    /// otherwise derived from the archive parameters and password and cached
    /// for the following block headers.
    pub(crate) fn archive_header_key(&mut self) -> RarResult<[u8; 32]> {
        if let Some(keys) = self.archive_keys.as_ref() {
            return Ok(keys.key);
        }
        let encr = self
            .archive_encr
            .as_ref()
            .ok_or_else(|| RarError::Format("no archive encryption params".into()))?;
        let password = self
            .password
            .as_deref()
            .ok_or_else(|| RarError::Encrypted("no password set".into()))?;
        let keys = encr.derive_keys(password)?;
        let key = keys.key;
        self.archive_keys = Some(keys);
        Ok(key)
    }

    // ── Read/Write context accessors ─────────────────────────────────────

    /// Immutable access to the read-side state. Panics if not opened for reading.
    pub(crate) fn read_ctx(&self) -> &ReadState {
        self.read.as_ref().expect("read context not available")
    }

    /// Mutable access to the read-side state. Panics if not opened for reading.
    pub(crate) fn read_ctx_mut(&mut self) -> &mut ReadState {
        self.read.as_mut().expect("read context not available")
    }

    /// Identity token of the current entry catalog (`0` until a catalog has
    /// been built). [`EntryId`]s embed this token; see
    /// [`ReadState::catalog_token`].
    pub(crate) fn catalog_token(&self) -> u64 {
        self.read_ctx().catalog_token
    }

    /// Immutable access to the write-side state. Panics if not opened for writing.
    pub(crate) fn write_ctx(&self) -> &WriteState {
        self.write.as_ref().expect("write context not available")
    }

    /// Mutable access to the write-side state. Panics if not opened for writing.
    pub(crate) fn write_ctx_mut(&mut self) -> &mut WriteState {
        self.write.as_mut().expect("write context not available")
    }

    /// Abort an in-progress staged write and disarm the legacy auto-commit
    /// behavior in [`Drop`]. Typed writer transactions use this seam for
    /// explicit abort-on-drop and poison-on-error semantics.
    ///
    /// [`Drop`] still runs [`Self::close`], so abort must also clear the
    /// recovery triggers: `close` regenerates `.rev` recovery volumes after
    /// the data volumes are committed, and an aborted transaction must never
    /// reach that step again (its volume set may not exist at all, or may
    /// have been only partially committed before an error).
    pub(crate) fn abort(&mut self) {
        self.stream = None;
        self.mode = Mode::Read;
        // This is an explicit abort of the operation, not a finalization
        // attempt: a later close may finalize (and, after an abort's cleanup,
        // find nothing to commit).
        self.finalize_started = false;
        self.recovery_volumes_percent = None;
        self.recovery_volumes_count = None;
        self.recovery_percent = None;
        if let Some(write) = self.write.as_mut() {
            // A deferred solid append must not repack on the abort path.
            write.rar4.solid_append = false;
            write.rar4.solid_append_entries.clear();
        }
        if let Some(pending) = self
            .write
            .as_mut()
            .and_then(|write| write.output.pending.take())
        {
            pending.cleanup(self.volume_paths.len());
        }
    }

    /// Open an existing RAR archive for reading.
    pub fn open(path: impl AsRef<Path>) -> RarResult<Self> {
        let mut archive = Self::new_for_mode(path.as_ref().to_path_buf(), Mode::Read, None);
        crate::format::shared::extract::open::open_read(&mut archive)?;
        Ok(archive)
    }

    /// Open an existing RAR5 archive for reading without a full block
    /// scan, using the quick-open record when present.
    ///
    /// Archives written with `quick_open` carry a cached copy of every
    /// file header; this opener reads only the main header + the QO
    /// record, so listing (`list` / `namelist`) is O(QO size) instead of
    /// O(archive size). Archives without a usable record (multi-volume,
    /// header-encrypted, or `-qo-`) transparently fall back to the full
    /// scan. Listing therefore always stays fast, while extraction first
    /// performs a header-only rescan (payload areas are skipped, never
    /// read) because the QO payload caches file headers only and would
    /// otherwise silently drop "STM" NTFS alternate data streams; after
    /// that, reading and extraction work identically to a full scan.
    pub fn open_quick(path: impl AsRef<Path>) -> RarResult<Self> {
        let mut archive = Self::new_for_mode(path.as_ref().to_path_buf(), Mode::Read, None);
        crate::format::shared::extract::open::open_read_quick(&mut archive)?;
        Ok(archive)
    }

    /// Open an existing RAR archive with a password for encrypted content.
    pub fn open_with_password(path: impl AsRef<Path>, password: &str) -> RarResult<Self> {
        let mut archive = Self::new_for_mode(
            path.as_ref().to_path_buf(),
            Mode::Read,
            Some(password.to_string()),
        );
        crate::format::shared::extract::open::open_read(&mut archive)?;
        Ok(archive)
    }

    /// Password variant of [`Self::open_quick`] (falls back to the full
    /// scan for header-encrypted archives, which never carry a QO record).
    pub fn open_quick_with_password(path: impl AsRef<Path>, password: &str) -> RarResult<Self> {
        let mut archive = Self::new_for_mode(
            path.as_ref().to_path_buf(),
            Mode::Read,
            Some(password.to_string()),
        );
        crate::format::shared::extract::open::open_read_quick(&mut archive)?;
        Ok(archive)
    }

    /// Set the password for decryption. In-crate test helper: public callers
    /// pass the password to [`ArchiveReader::open_with`] /
    /// [`ArchiveWriter::create_with`].
    #[cfg(test)]
    pub fn set_password(&mut self, password: &str) {
        self.password = Some(password.to_string());
        // A cached header key belongs to the previous password; the next
        // header operation must derive from the new one.
        self.archive_keys = None;
    }

    /// Open an existing single-volume RAR5 (RAR50/RAR70) archive for
    /// appending new members (like `rar a` on an existing archive). RAR4
    /// archives are rejected with [`RarError::Unsupported`]: appending
    /// requires the RAR5 container.
    ///
    /// Existing members are preserved verbatim: the trailing quick-open and
    /// recovery records are truncated, new members are written after the
    /// existing blocks, and [`Self::close`] rebuilds the quick-open record
    /// and the recovery record over the whole archive. Existing members are
    /// never recompressed.
    ///
    /// The append is staged in a temporary sibling file (the surviving
    /// prefix is copied over) and moved to the archive path only when
    /// [`Self::close`] succeeds, so a failed or interrupted append never
    /// truncates or corrupts the original archive.
    pub fn open_append(path: impl AsRef<Path>) -> RarResult<Self> {
        Self::open_append_with_password(path, "")
    }

    /// Set the dictionary used for members added to an already-open
    /// archive (WinRAR's `-md`; `None` = default selection). Applies to
    /// archives opened with `open_append*`, where the create options are
    /// not available.
    pub fn set_dictionary(
        &mut self,
        dict_size_log: Option<u8>,
        dict_size_bytes: Option<u64>,
    ) -> RarResult<()> {
        if self.mode == Mode::Read {
            return Err(RarError::InvalidState(
                "dictionary can only be set while writing or appending".into(),
            ));
        }
        crate::options::validate_dictionary(dict_size_log, dict_size_bytes)?;
        if self.is_rar4() && dict_size_bytes.is_some() {
            return Err(RarError::InvalidOption(
                "RAR4 does not support byte-sized RAR7 dictionaries".into(),
            ));
        }
        let write = self
            .write
            .as_mut()
            .ok_or_else(|| RarError::InvalidState("write context is not available".into()))?;
        write.compression.dict_size_log = dict_size_log;
        write.compression.dict_size_bytes = dict_size_bytes;
        Ok(())
    }

    /// Open an existing archive for appending, with a password for
    /// encrypted content.
    pub fn open_append_with_password(path: impl AsRef<Path>, password: &str) -> RarResult<Self> {
        let pw = if password.is_empty() {
            None
        } else {
            Some(password.to_string())
        };
        let mut archive = Self::new_for_mode(path.as_ref().to_path_buf(), Mode::Append, pw);
        if let Err(error) = crate::format::shared::extract::open::open_read(&mut archive)
            .and_then(|()| archive.prepare_append())
        {
            archive.abort();
            return Err(error);
        }
        Ok(archive)
    }

    /// Prepare an archive for appending: verify it is modifiable, capture
    /// the main header locator state, cache the existing file headers for
    /// the rebuilt quick-open record, and truncate the trailing end /
    /// quick-open / recovery blocks.
    fn prepare_append(&mut self) -> RarResult<()> {
        if self.is_rar13() {
            return Err(RarError::Unsupported(
                "appending to RAR 1.3/1.4 archives is not supported".into(),
            ));
        }
        // Recover a multi-volume commit another process was killed in the
        // middle of before touching this archive.
        let parent = self.path.parent().unwrap_or(Path::new(".")).to_path_buf();
        crate::fs::atomic::recover_interrupted_commit(
            &parent,
            &crate::fs::volume::volume_base_of(&self.path),
        )?;
        // The RAR5 path stages a rewrite: re-parse RAR5 block headers,
        // rebuild the quick-open record and patch the RAR5 main-header
        // locator. The RAR4 path (ADR 0005 stage B) has its own prelude
        // below instead of misparsing fixed-width headers.
        if self.is_rar4() {
            // RAR4 append (ADR 0005 stage B): gate on the main-header
            // flags, drop the trailing NEWSUB record / end-of-archive block
            // (rebuilding the record at close when the archive had one),
            // and stage the surviving prefix into a temporary sibling.
            let prelude = crate::archive::rar4_edit::append_prelude(self)?;
            self.write_ctx_mut().rar4.rr_sectors = prelude.rr_sectors;
            if prelude.header_encrypted {
                // `-hp`: the blocks appended below (members, recovery
                // record, end-of-archive) are header-encrypted with the
                // archive password, like everything already in the file.
                self.header_encryption = true;
            }
            if prelude.solid {
                // A solid chain cannot be streamed after: defer the append
                // to a whole-archive repack at close (the additions are
                // buffered in the write context). The original file is left
                // untouched until the repack replaces it atomically.
                self.write_ctx_mut().rar4.solid_append = true;
                self.write_ctx_mut().rar4.solid_append_entries.clear();
                return Ok(());
            }
            let path = self.path.clone();
            let tmp_path = temp_sibling_path(&path);
            self.write_ctx_mut().output.pending = Some(PendingCommit::Single(tmp_path.clone()));
            let mut src = File::open(&path)?;
            let mut dst = read_write_create(&tmp_path)?;
            copy_prefix(
                &mut src,
                &mut dst,
                prelude
                    .truncate_pos
                    .expect("non-solid prelude carries a truncation point"),
            )?;
            self.stream = Some(Box::new(dst));
            return Ok(());
        }
        if self.volume_paths.len() > 1 {
            return Err(RarError::Unsupported(
                "appending to multi-volume archives is not supported (the official rar refuses too)"
                    .into(),
            ));
        }
        let path = self.path.clone();
        let mut reader = File::open(&path)?;
        let file_len = reader.metadata().map_err(RarError::Io)?.len();

        let main = crate::format::rar5::extract::open::read_main_header(self, &mut reader)?;
        let ah = main.parsed;
        if ah.flags & ARCHIVE_FLAG_LOCKED != 0 {
            return Err(RarError::ArchiveLocked);
        }
        let (had_qo, had_rr, _) = split_main_extra(&ah.extra_data)?;
        let (qo_field_pos, rr_field_pos) = main_header_locator_fields(&main.meta)?;
        self.write_ctx_mut().locator.main_header_start = Some(main.meta.block_start);
        self.write_ctx_mut().locator.qo_offset_field_pos = qo_field_pos.map(|p| p as u64);
        self.write_ctx_mut().locator.rr_offset_field_pos = rr_field_pos.map(|p| p as u64);
        self.write_ctx_mut().locator.quick_open = had_qo && !self.header_encryption;

        // Walk the remaining blocks: cache existing headers for the rebuilt
        // quick-open record and find the truncation point (the first
        // trailing QO/RR service block, or the end block).
        let mut truncate_pos = None;
        let mut last_file_end = 0u64;
        let mut rr_percent = None;
        let mut blocks = BlockCursor::new(
            file_len,
            crate::format::rar5::extract::verify::archive_block_key(self)?,
        );
        while let Some(meta) = blocks.next(&mut reader)? {
            match meta.block_type {
                BLOCK_TYPE_END_ARCHIVE => {
                    if truncate_pos.is_none() {
                        truncate_pos = Some(meta.block_start);
                    }
                    break;
                }
                BLOCK_TYPE_FILE_HEADER => {
                    if self.write_ctx().locator.quick_open {
                        self.write_ctx_mut()
                            .locator
                            .quick_open_entries
                            .push((meta.block_start, meta.header_bytes.clone()));
                    }
                    last_file_end = meta.data_end;
                }
                BLOCK_TYPE_SERVICE_HEADER => {
                    let name = parse_service_block_name(&meta.raw.header_data)?;
                    if name.as_deref() == Some("RR") {
                        rr_percent = parse_service_recovery_percent(&meta.raw.header_data);
                    }
                    if (name.as_deref() == Some("QO") || name.as_deref() == Some("RR"))
                        && meta.block_start >= last_file_end
                        && truncate_pos.is_none()
                    {
                        truncate_pos = Some(meta.block_start);
                    }
                }
                _ => {}
            }
        }
        let truncate_pos = truncate_pos.unwrap_or(last_file_end);

        self.recovery_percent = if had_rr { rr_percent } else { None };

        // Stage the append: copy the surviving prefix into a temporary
        // sibling file and append the new members there. The temp is moved
        // over the archive on close, so a failed or interrupted append
        // never truncates or corrupts the original archive.
        let tmp_path = temp_sibling_path(&path);
        self.write_ctx_mut().output.pending = Some(PendingCommit::Single(tmp_path.clone()));
        let mut src = File::open(&path)?;
        let mut dst = read_write_create(&tmp_path)?;
        copy_prefix(&mut src, &mut dst, truncate_pos)?;
        self.stream = Some(Box::new(dst));
        Ok(())
    }

    /// Lock the archive (like `rar k`): sets the `LOCKED` flag in the main
    /// archive header, making the archive read-only. Locking is
    /// irreversible.
    ///
    /// The patched prefix is staged in a temporary sibling and installed over
    /// the archive only when it is complete and flushed, so a crash or a
    /// failed install leaves the original archive untouched instead of a
    /// header with a stale CRC. The in-place stream is not touched: the read
    /// side opens it lazily per operation.
    pub(crate) fn lock(&mut self) -> RarResult<()> {
        if self.mode != Mode::Read {
            return Err(RarError::Format(
                "lock requires an archive opened for reading".into(),
            ));
        }
        if self.volume_paths.len() > 1 {
            return Err(RarError::Unsupported(
                "locking multi-volume archives is not supported (lock the first volume instead)"
                    .into(),
            ));
        }
        if self.main_header_is_locked()? {
            return Ok(());
        }
        let path = self.path.clone();
        let mut reader = File::open(&path)?;
        let main_meta =
            crate::format::rar5::extract::open::read_main_header(self, &mut reader)?.meta;

        // Patch the archive-level flags in the plaintext header and
        // recompute the CRC. The flags field lives in the header body at
        // `offset`; the on-disk header is `[crc 4][size vint][body]` (or an
        // IV + ciphertext when header-encrypted, rebuilt below).
        let data = &main_meta.raw.header_data;
        let mut offset = 0usize;
        let (_, n) = vint::decode_from_slice(data, offset)
            .map_err(|e| RarError::Format(format!("block type: {e}")))?;
        offset += n;
        let (flags, n) = vint::decode_from_slice(data, offset)
            .map_err(|e| RarError::Format(format!("block flags: {e}")))?;
        offset += n;
        if flags & BLOCK_FLAG_EXTRA_DATA != 0 {
            let (_, n) = vint::decode_from_slice(data, offset)
                .map_err(|e| RarError::Format(format!("extra size: {e}")))?;
            offset += n;
        }
        let (arch_flags, vint_len) = vint::decode_from_slice(data, offset)
            .map_err(|e| RarError::Format(format!("archive flags: {e}")))?;
        let new_flags = arch_flags | ARCHIVE_FLAG_LOCKED;
        let new_vint = vint::encode(new_flags);
        if new_vint.len() != vint_len {
            return Err(RarError::Unsupported(
                "cannot lock: the archive flags field grows when locked".into(),
            ));
        }
        let mut body = main_meta.raw.header_data.clone();
        body[offset..offset + vint_len].copy_from_slice(&new_vint);
        let plain = crate::format::rar5::headers::frame_block(&body);

        // Stage the archive start up to the main header, the re-encoded main
        // header, and the untouched tail into a temporary sibling; streaming
        // keeps memory bounded for multi-GB archives and the original is
        // untouched until the flushed stage replaces it. Header-encrypted
        // archives get a fresh IV (the on-disk header is `[IV][ciphertext]`);
        // the key is derived once and cached.
        let main_start = main_meta.block_start;
        let main_end = main_meta.data_offset;
        let header_key = if self.header_encryption {
            Some(self.archive_header_key()?)
        } else {
            None
        };
        stage_file(
            &path,
            |out| {
                let mut reader = File::open(&path)?;
                copy_prefix(&mut reader, out, main_start)?;
                if let Some(key) = header_key.as_ref() {
                    let mut iv = [0u8; ENCR_IV_SIZE];
                    rand::fill(&mut iv);
                    out.write_all(&iv)?;
                    out.write_all(&crypto::encrypt_data(&plain, key, &iv))?;
                } else {
                    out.write_all(&plain)?;
                }
                let file_len = reader.metadata().map_err(RarError::Io)?.len();
                if file_len < main_end {
                    return Err(RarError::Format(
                        "archive tail lies past the end of the archive".into(),
                    ));
                }
                reader.seek(SeekFrom::Start(main_end))?;
                copy_prefix(&mut reader, out, file_len - main_end)?;
                Ok(())
            },
            install_durable,
        )
    }

    /// Create a new RAR archive with explicit options (overwrites an
    /// existing file).
    ///
    /// This is the full-featured constructor: `solid`, `quick_open` and
    /// `blake2` options can be combined with passwords, header encryption,
    /// recovery records and volume sizes.
    ///
    /// The archive data is staged in a temporary sibling file and moved to
    /// `path` only when [`Self::close`] succeeds, so an aborted or failed
    /// write never leaves a partial archive at `path`.
    pub(crate) fn create_with_options(
        path: impl AsRef<Path>,
        opts: crate::options::CreateOptions,
    ) -> RarResult<Self> {
        let path = path.as_ref().to_path_buf();
        let mut archive = Self::new_with_options(path, opts)?;
        if let Err(error) = archive.open_write() {
            archive.abort();
            return Err(error);
        }
        Ok(archive)
    }

    /// Create an archive writing into a caller-provided seekable sink
    /// (test seam; `Cursor<Vec<u8>>` gives an in-memory archive). The sink
    /// can be recovered with [`Self::finish_into_sink`] after closing.
    #[cfg(test)]
    pub(crate) fn create_with_sink(
        path: PathBuf,
        opts: crate::options::CreateOptions,
        sink: Box<dyn ArchiveStream>,
    ) -> RarResult<Self> {
        if opts.volume_size.is_some() {
            return Err(RarError::Unsupported(
                "in-memory sinks are single-volume only".into(),
            ));
        }
        if opts.compression.is_rar13() {
            return Err(RarError::Unsupported(
                "in-memory sinks are not supported for RAR 1.3/1.4 archives".into(),
            ));
        }
        if opts.recovery_volumes_percent.is_some() || opts.recovery_volume_count.is_some() {
            return Err(RarError::Unsupported(
                "recovery volumes require files on disk".into(),
            ));
        }
        let mut archive = Self::new_with_options(path, opts)?;
        archive.stream = Some(sink);
        archive.write_signature()?;
        archive.write_archive_encryption_header_if_needed()?;
        archive.write_archive_header()?;
        Ok(archive)
    }

    /// Validate options and build the archive state (without opening the
    /// stream).
    fn new_with_options(path: PathBuf, opts: crate::options::CreateOptions) -> RarResult<Self> {
        opts.validate()?;
        let is_rar4 = opts.compression.is_legacy();
        let is_rar13 = opts.compression.is_rar13();
        // Family-specific policy (options a container cannot express) is
        // validated through the one seam both write surfaces share, so this
        // layer carries no duplicated rule set and reports the same
        // `InvalidOption` the typed `WriterOptions` surface does.
        create::validate_write_options(
            opts.compression,
            &create::WriteOptionFlags::from_create(&opts),
        )?;
        // Header encryption is supported for multi-volume archives: every
        // volume starts with the plaintext encryption header and all
        // subsequent blocks are `[IV][AES-256-CBC header]` (WinRAR -hp
        // convention). The combination rules (header encryption without a
        // password, quick-open with volumes or header encryption, recovery
        // records or volumes with the wrong volume setting) were already
        // rejected by `validate` with the same wording as `WriterOptions`.
        let quick_open = opts.quick_open;

        let archive = RarArchive {
            path,
            mode: Mode::Write,
            finalize_started: false,
            entries: Vec::new(),
            sfx_offset: 0,
            family: if is_rar13 {
                crate::detect::ArchiveFamily::Rar13
            } else if is_rar4 {
                crate::detect::ArchiveFamily::Rar15To40
            } else {
                crate::detect::ArchiveFamily::Rar50Plus
            },
            archive_solid: false,
            stream: None,
            password: opts.password,
            header_encryption: opts.encrypt_headers,
            archive_encr: None,
            archive_keys: None,
            recovery_percent: opts.recovery_percent,
            recovery_volumes_percent: opts.recovery_volumes_percent,
            recovery_volumes_count: opts.recovery_volume_count,
            cancel: None,
            volume_paths: Vec::new(),
            progress: None,
            progress_member: 0,
            read: None,
            write: Some(WriteState {
                solid: SolidChain {
                    mode: opts.solid,
                    reset: opts.solid_reset,
                    last_ext: None,
                    encoder_state: None,
                    chain_dict: None,
                    rar4_encoder: None,
                    legacy_encoder: None,
                    rar4_unp_ver: if is_rar4 {
                        opts.compression.to_unp_ver().unwrap_or(29)
                    } else {
                        0
                    },
                    rar4_run_has_member: false,
                },
                rar4: Rar4Append::default(),
                compression: CompressionSettings {
                    threads: opts.threads,
                    dict_size_log: opts.dict_size_log,
                    dict_size_bytes: opts.dict_size_bytes,
                    force_v70: opts.force_v70,
                    filters: opts.filters,
                },
                meta: MetadataSettings {
                    ctime: opts.save_ctime,
                    atime: opts.save_atime,
                    mtime: opts.save_mtime,
                    owner: opts.save_owner,
                    streams: opts.save_streams,
                    time_precision_seconds: opts.time_precision_seconds,
                    blake2: opts.blake2,
                },
                locator: LocatorState {
                    quick_open,
                    quick_open_entries: Vec::new(),
                    qo_offset_field_pos: None,
                    main_header_start: None,
                    rr_offset_field_pos: None,
                },
                output: OutputState {
                    pending: None,
                    volume_size: opts.volume_size,
                    current_volume: 0,
                    bytes_written: 0,
                    rar13_header_pending: false,
                },
            }),
        };
        Ok(archive)
    }

    // ── Progress ──────────────────────────────────────────────────────────

    /// Set an optional progress callback for archive creation.
    ///
    /// The callback receives `(bytes_committed, bytes_total)` where
    /// `bytes_total` is the total input byte count of the whole write
    /// operation (a single member, or the full batch passed to
    /// `RarArchive::add_batch`) and `bytes_committed` is the monotonic,
    /// operation-global number of input bytes processed so far. Events are
    /// delivered serially even when members compress concurrently on the
    /// Rayon pool, and `bytes_committed` never moves backwards.
    ///
    /// Callers no longer need to stitch per-file deltas together: the
    /// reported percentage is `bytes_committed / bytes_total` directly.
    pub fn set_progress_callback(&mut self, callback: Option<Box<dyn FnMut(u64, u64) + Send>>) {
        self.progress = callback
            .map(|cb| std::sync::Arc::new(std::sync::Mutex::new(ProgressTracker::new(Some(cb)))));
        self.progress_member = 0;
    }

    /// Override the progress denominator. `add_batch` sets this automatically
    /// to the sum of its members' sizes; single-member `add_*` calls fall back
    /// to the member's own size when this is left unset.
    pub fn set_progress_total(&mut self, total: u64) {
        if let Some(progress) = &self.progress {
            progress.lock().expect("progress lock").set_total(total);
        }
    }
}

/// Replace `dest` with the contents of a temporary sibling filled by
/// `write_staged`: the bytes are flushed before the install, and a failed
/// install (or a failed fill) removes the temporary file, leaving `dest`
/// untouched. Used by the archive lock path, which must never leave a header
/// with a stale CRC at the archive path.
fn stage_file(
    dest: &Path,
    write_staged: impl FnOnce(&mut File) -> RarResult<()>,
    install: impl FnOnce(&Path, &Path) -> RarResult<()>,
) -> RarResult<()> {
    let tmp_path = temp_sibling_path(dest);
    let staged = (|| -> RarResult<()> {
        let mut file = read_write_create(&tmp_path)?;
        write_staged(&mut file)?;
        file.sync_all().map_err(RarError::Io)
    })();
    let installed = staged.and_then(|()| install(&tmp_path, dest));
    if installed.is_err() {
        let _ = std::fs::remove_file(&tmp_path);
    }
    installed
}

/// Project the plain [`crate::options::CreateOptions`] struct onto the
impl Drop for RarArchive {
    fn drop(&mut self) {
        // Once finalization has been attempted, never re-enter it: a failed
        // or partial finalize may have left the stream mid-write, and a
        // retry would corrupt the archive. The caller already saw the error.
        if !self.finalize_started {
            let _ = self.close();
        }
        // `close` may have failed (or never been reached); remove any
        // staged files that were not committed so a failed or interrupted
        // write leaves no garbage behind and never a partial archive at
        // the final path. A read-only archive has no write context.
        if let Some(pending) = self.write.as_mut().and_then(|w| w.output.pending.take()) {
            pending.cleanup(self.volume_paths.len());
        }
    }
}
