//! External cross-validation against a real WinRAR-produced RAR5 archive that
//! carries a genuine data-recovery record.
//!
//! The fixture `fixtures/rar50/winrar5_with_recovery_rr5.rar` was created with
//! `WinRAR RAR 7.23` (`Rar.exe a -rr5% -ma5 -s- -m5 -ep doc.txt data.bin`), so
//! it exercises the *real* RAR5 inline-recovery-record format rather than our
//! own writer. Two things must hold for the cross-validation to pass:
//!
//! 1. Our reader decodes WinRAR's members (proving our RAR5 parser handles the
//!    vendor's output, including locating the `RR` service header).
//! 2. Our recovery/repair engine reconstructs the WinRAR-produced parity when
//!    the archive is damaged, returning byte-identical original bytes.

use rar_rs::{ArchiveReader, repair_archive};
use std::path::PathBuf;

fn fixture_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures/rar50/winrar5_with_recovery_rr5.rar")
}

#[test]
fn winrar_rar5_recovery_record_parses_and_decodes() {
    // Guard: the fixture really carries an inline recovery record.
    let raw = include_bytes!("fixtures/rar50/winrar5_with_recovery_rr5.rar");
    let text = String::from_utf8_lossy(raw);
    assert!(text.contains("RR"), "fixture must contain an RR service header");
    assert!(text.contains("{RB}"), "fixture must contain an {{RB}} recovery chunk");

    // Our reader must decode WinRAR's members correctly.
    let mut reader = ArchiveReader::open(fixture_path()).expect("open WinRAR RAR5 archive");
    assert_eq!(reader.entries().len(), 2, "expected doc.txt + data.bin");

    let doc_id = reader.unique_entry("doc.txt").expect("doc.txt entry");
    let doc = reader.read_entry(doc_id).expect("read doc.txt");
    assert_eq!(doc.len(), 304000, "doc.txt size must match source");
    let prefix = b"RAR5 recovery record cross-validation fixture generated by WinRAR RAR 7.23. ";
    assert_eq!(
        &doc[..prefix.len()],
        prefix,
        "doc.txt content must match WinRAR source"
    );

    let data_id = reader.unique_entry("data.bin").expect("data.bin entry");
    let data = reader.read_entry(data_id).expect("read data.bin");
    assert_eq!(data.len(), 65536, "data.bin size must match source");
}

#[test]
fn winrar_rar5_recovery_record_repairs_damaged_archive() {
    let raw = include_bytes!("fixtures/rar50/winrar5_with_recovery_rr5.rar");
    // Guard: the fixture really carries an inline recovery record.
    let text = String::from_utf8_lossy(raw);
    assert!(
        text.contains("RR") && text.contains("{RB}"),
        "fixture must carry an RR service header and {{RB}} recovery chunk"
    );

    // Damage a single byte well inside the protected prefix (never inside the
    // recovery record itself, which lives at the very end of the archive).
    let mut damaged = raw.to_vec();
    let pos = raw.len() / 4;
    damaged[pos] ^= 0xFF;

    // Our repair engine must reconstruct the WinRAR-produced parity and return
    // the original bytes unchanged.
    let repaired = repair_archive(&damaged).expect("repair WinRAR recovery record");
    assert_eq!(
        repaired, raw,
        "repair must restore the original WinRAR-produced bytes"
    );
}
