'use strict'

/**
 * The public entry point of the `rar-rs` Node binding.
 *
 * `binding.js` (gitignored) is generated by `napi build --platform --js
 * binding.js`, so this file must never be generated: it is the layer that
 * turns the binding's N-API errors into a real `RarError`, and it is free to
 * add convenience wrappers without fighting the generator.
 *
 * The binding reports only a coarse N-API status, because napi-rs builds
 * every thrown error through `napi_create_error`, whose sole configurable
 * field is `code` (locked to the status string). The precise category
 * therefore travels inside the message as `[rar-rs:<code>] …`; see
 * `src/error.rs` for the Rust half and keep the `RarErrorCode` list below in
 * sync with it and with `rar-rs.d.ts`.
 */

const binding = require('./binding.js')

/** Every value `error.rarCode` can hold, in `src/error.rs` order. */
const RAR_ERROR_CODES = Object.freeze([
  'format',
  'invalid_state',
  'invalid_option',
  'crc_mismatch',
  'hash_mismatch',
  'encrypted',
  'unsupported',
  'security',
  'limit_exceeded',
  'member_not_found',
  'ambiguous_member',
  'stale_entry_id',
  'archive_locked',
  'cancelled',
  'wrong_password',
  'create',
  'io',
  'internal',
])

/** Matches the marker `src/error.rs` prepends, capturing the code. */
const CODE_MARKER = /^\[rar-rs:([a-z][a-z0-9_]*(?:_[a-z0-9]+)*)\]\s?/

/**
 * The code for a rejection the binding built itself, with no marker.
 *
 * The binding validates scalar arguments (`level`, `threads`, `volumeSize`,
 * an entry's `kind`/`path`/`data`) before the library ever sees them, and
 * reports those as a bare `InvalidArg` — a `TypeError`-class failure the
 * caller can fix. An unmarked `GenericFailure` or `Cancelled` is not this
 * case, so it stays `'internal'`.
 */
const BINDING_ARGUMENT_CODE = 'invalid_option'

/**
 * The error class every rejected binding call produces.
 *
 * `code` mirrors the N-API status napi-rs assigned (kept for callers that
 * already branch on `'InvalidArg'` / `'GenericFailure'` / `'Cancelled'`),
 * while `rarCode` is the stable, finer-grained library category — the same
 * classification the CLI maps onto its process exit codes.
 */
class RarError extends Error {
  constructor(message, options = {}) {
    super(message, options.cause === undefined ? undefined : { cause: options.cause })
    this.name = 'RarError'
    /** The N-API status string, e.g. `'InvalidArg'`. */
    this.code = options.status
    /**
     * The stable library error category, e.g. `'wrong_password'`.
     *
     * `'internal'` means the binding itself failed (a Rust panic caught by
     * its firewall), not the archive or the arguments.
     */
    this.rarCode = options.rarCode
  }
}

/**
 * Rebuild a binding rejection as a `RarError`.
 *
 * Anything that is not a thrown `Error`-shaped object (a string rejection, a
 * `TypeError` from argument coercion) is passed through untouched.
 */
function rehydrate(error) {
  if (!error || typeof error !== 'object' || typeof error.message !== 'string') {
    return error
  }
  const status = typeof error.code === 'string' ? error.code : undefined
  const match = CODE_MARKER.exec(error.message)
  const rarCode = match
    ? match[1]
    : status === 'InvalidArg'
      ? BINDING_ARGUMENT_CODE
      : 'internal'
  const message = match ? error.message.slice(match[0].length) : error.message
  const rebased = new RarError(message, { cause: error.cause, status, rarCode })
  if (typeof error.stack === 'string') {
    // Rebase the header line so the stack names this class and the cleaned
    // message; the binding frames below it are unchanged and still useful.
    const frames = error.stack.slice(error.stack.indexOf('\n'))
    rebased.stack = `${rebased.name}: ${rebased.message}${frames}`
  }
  // `cause` is already carried by the constructor; keep any other extra field
  // the binding attached (none today, but an `errors` aggregate would be).
  if (error.errors !== undefined) rebased.errors = error.errors
  return rebased
}

/**
 * Wrap a binding export so a thrown error becomes a `RarError`.
 *
 * Works for both the sync and the `AsyncTask` exports: a rejected promise is
 * re-mapped in the same way as a synchronous throw, so a caller never sees a
 * raw binding error on either path.
 */
function guard(fn) {
  return function guarded(...args) {
    let result
    try {
      result = fn.apply(this, args)
    } catch (error) {
      throw rehydrate(error)
    }
    return result && typeof result.then === 'function'
      ? result.then(undefined, (error) => {
          throw rehydrate(error)
        })
      : result
  }
}

/**
 * Whether `value` is an error produced by this binding.
 *
 * Prefer testing `error.rarCode` for a specific case; use this to tell a
 * binding failure from an unrelated `TypeError` in your own code. Accepts an
 * error from a different copy of this module as well, by checking the code
 * rather than only the class.
 */
function isRarError(value) {
  if (value instanceof RarError) return true
  return (
    typeof value === 'object' &&
    value !== null &&
    typeof value.rarCode === 'string' &&
    RAR_ERROR_CODES.includes(value.rarCode)
  )
}

/** Whether `value` is a cancellation (`AbortSignal`, or the `cancelled` code). */
function isCancellationError(value) {
  if (!value || typeof value !== 'object') return false
  return value.rarCode === 'cancelled' || value.code === 'Cancelled'
}

/**
 * The exported operations, spelled out.
 *
 * Node's ESM loader only exposes named exports it can find statically in a
 * CommonJS module (`cjs-module-lexer`), so a dynamic loop over the binding's
 * keys would silently turn every name into a default-only export. The list
 * below is therefore explicit, and `assertExportCoverage()` keeps it honest
 * by failing loudly if the binding gains an export this file does not wrap.
 */
const OPERATION_EXPORTS = [
  'appendEntries',
  'createArchive',
  'deleteEntries',
  'extractArchive',
  'extractMember',
  'listEntries',
  'listEntriesDetailed',
  'listEntriesQuick',
  'lockArchive',
  'readMember',
  'rebuildMissingVolumes',
  'renameEntries',
  'repairArchive',
  'setComment',
  'setMemberComment',
  'setRecovery',
  'testArchive',
]

/** Wraps every operation and copies it onto `module.exports` by name. */
function installExports(target, source) {
  for (const name of OPERATION_EXPORTS) {
    const value = source[name]
    if (typeof value !== 'function') {
      throw new Error(
        `rar-rs: the binding does not export \`${name}\`; rebuild with \`npm run build\``,
      )
    }
    target[name] = guard(value)
  }
}

/**
 * Fail loudly when the binding gains an operation this entry point does not
 * wrap — otherwise it would be reachable only through the generated
 * `binding.js`, silently bypassing the `RarError` mapping.
 */
function assertExportCoverage(source) {
  const known = new Set(OPERATION_EXPORTS)
  const unwrapped = Object.keys(source).filter(
    (name) => typeof source[name] === 'function' && !known.has(name) && !name.endsWith('Task'),
  )
  if (unwrapped.length > 0) {
    throw new Error(
      `rar-rs: the binding exports ${unwrapped.join(', ')} but \`rar-rs.js\` does not wrap ` +
        'them; add them to OPERATION_EXPORTS so their errors become `RarError`s',
    )
  }
}

// Every operation is wrapped, so no binding error escapes unrehydrated, and
// each is assigned with a literal `module.exports.<name> =` statement because
// Node's `cjs-module-lexer` only reports named exports it can read statically
// (see OPERATION_EXPORTS).
const wrapped = {}
installExports(wrapped, binding)
assertExportCoverage(binding)

module.exports.appendEntries = wrapped.appendEntries
module.exports.createArchive = wrapped.createArchive
module.exports.deleteEntries = wrapped.deleteEntries
module.exports.extractArchive = wrapped.extractArchive
module.exports.extractMember = wrapped.extractMember
module.exports.listEntries = wrapped.listEntries
module.exports.listEntriesDetailed = wrapped.listEntriesDetailed
module.exports.listEntriesQuick = wrapped.listEntriesQuick
module.exports.lockArchive = wrapped.lockArchive
module.exports.readMember = wrapped.readMember
module.exports.rebuildMissingVolumes = wrapped.rebuildMissingVolumes
module.exports.renameEntries = wrapped.renameEntries
module.exports.repairArchive = wrapped.repairArchive
module.exports.setComment = wrapped.setComment
module.exports.setMemberComment = wrapped.setMemberComment
module.exports.setRecovery = wrapped.setRecovery
module.exports.testArchive = wrapped.testArchive
module.exports.RarError = RarError
module.exports.RAR_ERROR_CODES = RAR_ERROR_CODES
module.exports.isRarError = isRarError
module.exports.isCancellationError = isCancellationError
