/**
 * Type definitions for `rar-rs`, the Node binding of the pure-Rust RAR
 * toolkit.
 *
 * `binding.d.ts` (gitignored) is generated by `napi build --dts binding.d.ts`
 * and describes the Rust surface verbatim. This file is the hand-written
 * public surface: it re-exports the data types from the generated module and
 * declares the functions with the signatures this package actually presents
 * (napi-rs emits a Node-style leading `err` parameter for progress callbacks
 * that is always `null`).
 *
 * Keep `RarErrorCode` in sync with `RAR_ERROR_CODES` in `rar-rs.js` and with
 * `STABLE_CODES` in `src/error.rs`.
 */

import type {
  AppendArchiveOptions,
  CreateArchiveOptions,
  CreateResult,
  ExtractArchiveOptions,
  ExtractionResult,
  RenameEntry,
} from './binding.js'

export type {
  AppendArchiveOptions,
  CreateArchiveOptions,
  CreateResult,
  EntryInfo,
  EntryInput,
  ExtractArchiveOptions,
  ExtractionResult,
  MemberFailure,
  RenameEntry,
} from './binding.js'

/**
 * The stable category of a failure, matching the library's `ErrorCode`.
 *
 * This is the value to branch on: it survives library and binding releases,
 * unlike the message text. `'internal'` means the binding itself failed (a
 * Rust panic caught by its firewall), not the archive or the arguments.
 */
export type RarErrorCode =
  | 'format'
  | 'invalid_state'
  | 'invalid_option'
  | 'crc_mismatch'
  | 'hash_mismatch'
  | 'encrypted'
  | 'unsupported'
  | 'security'
  | 'limit_exceeded'
  | 'member_not_found'
  | 'ambiguous_member'
  | 'stale_entry_id'
  | 'archive_locked'
  | 'cancelled'
  | 'wrong_password'
  | 'create'
  | 'io'
  | 'internal'

/** Every value `error.rarCode` can hold, at runtime. */
export const RAR_ERROR_CODES: readonly RarErrorCode[]

/**
 * The error every rejected `rar-rs` call produces.
 *
 * - `rarCode` is the stable library category ({@link RarErrorCode}).
 * - `code` is the N-API status napi-rs assigned (`'InvalidArg'`,
 *   `'GenericFailure'`, `'Cancelled'`), kept so existing checks keep working.
 */
export class RarError extends Error {
  constructor(
    message: string,
    options?: { cause?: unknown; status?: string | undefined; rarCode?: RarErrorCode },
  )
  /** The N-API status string, e.g. `'InvalidArg'`. */
  code: string | undefined
  /** The stable library category, e.g. `'wrong_password'`. */
  rarCode: RarErrorCode
  /** Present when the transport attached an aggregate of nested failures. */
  errors?: unknown[]
}

/**
 * Whether `value` is an error produced by this binding.
 *
 * Works across copies of the module (it checks `rarCode`, not only the class),
 * so it is the right guard in a library that may be loaded twice.
 */
export function isRarError(value: unknown): value is RarError

/** Whether `value` is a cancellation, from an `AbortSignal` or otherwise. */
export function isCancellationError(value: unknown): boolean

/**
 * Progress event shape, re-declared with units.
 *
 * `done`/`total` are **bytes**: the whole operation's for `createArchive`,
 * `appendEntries` and `extractArchive` (use `done / total`), and the current
 * member's for `extractMember`.
 */
export interface ProgressData {
  /** Bytes processed so far; never decreases. */
  done: number
  /** Bytes expected in total; `0` when the operation cannot know it upfront. */
  total: number
}

/**
 * Progress callback as this package delivers it.
 *
 * napi-rs's generated signature passes a leading Node-style `err`, which is
 * always `null` for a progress event; this alias is the ergonomic form.
 */
export type ProgressCallback = (progress: ProgressData) => void

/* ── Operations ─────────────────────────────────────────────────────────────
 * Declared here rather than re-exported so each carries its real
 * TypeScript shape and a doc comment a caller can act on. */

/**
 * Create an archive at `opts.outPath`.
 *
 * Rejects with {@link RarError} (`error.rarCode`); resolves with the paths of
 * every file produced, which for a multi-volume set is the whole set.
 */
export declare function createArchive(
  opts: CreateArchiveOptions,
  onProgress?: ProgressCallback | null,
  signal?: AbortSignal | null,
): Promise<CreateResult>

/**
 * Append entries to an existing archive.
 *
 * Single-volume only: appending to a multi-volume set is refused, like the
 * official tool. Rejects with {@link RarError}.
 */
export declare function appendEntries(
  opts: AppendArchiveOptions,
  onProgress?: ProgressCallback | null,
  signal?: AbortSignal | null,
): Promise<CreateResult>

/**
 * List stored member names, in archive order.
 *
 * `password` is only needed for a header-encrypted archive. Rejects with
 * {@link RarError}.
 */
export declare function listEntries(
  archivePath: string,
  password?: string | null,
): Promise<string[]>

/** List members with their metadata (see `EntryInfo` for the units). */
export declare function listEntriesDetailed(
  archivePath: string,
  password?: string | null,
): Promise<import('./binding.js').EntryInfo[]>

/**
 * List members using the archive's quick-open record when it has one, falling
 * back to a full scan otherwise.
 */
export declare function listEntriesQuick(
  archivePath: string,
  password?: string | null,
): Promise<import('./binding.js').EntryInfo[]>

/**
 * Read one member's uncompressed content into memory.
 *
 * Bounded by the library's 4 GiB per-member read limit; use
 * {@link extractMember} or {@link extractArchive} for arbitrarily large
 * members, which stream to disk.
 */
export declare function readMember(
  archivePath: string,
  name: string,
  password?: string | null,
): Promise<Buffer>

/**
 * Extract one member into `destDir`, streaming to disk.
 *
 * Resolves with the resolved output path. The name must identify the member
 * uniquely. No progress callback: the single member either lands or fails, and
 * a caller that needs progress through a long extraction should use
 * {@link extractArchive}.
 */
export declare function extractMember(
  archivePath: string,
  name: string,
  destDir: string,
  password?: string | null,
  signal?: AbortSignal | null,
): Promise<string>

/**
 * Extract an archive into `opts.destPath`.
 *
 * Resolves with what the run did member by member
 * ({@link ExtractionResult}). By default the first failing member rejects the
 * call (WinRAR's behaviour); with `opts.collectErrors` set, the call resolves
 * and names every failure in `failures` instead. A cancellation always
 * rejects.
 */
export declare function extractArchive(
  archivePath: string,
  opts: ExtractArchiveOptions,
  onProgress?: ProgressCallback | null,
  signal?: AbortSignal | null,
): Promise<ExtractionResult>

/**
 * Test every member's integrity.
 *
 * Resolves with `[checked, failed]` counts; a damaged member is reported, not
 * thrown. Use `listEntriesDetailed` plus this call to name the member.
 */
export declare function testArchive(
  archivePath: string,
  password?: string | null,
): Promise<number[]>

/**
 * Delete members without rebuilding the archive.
 *
 * Resolves with the number deleted. Fails when any requested name is absent,
 * or when the archive is locked or multi-volume.
 */
export declare function deleteEntries(
  archivePath: string,
  names: string[],
  password?: string | null,
  onProgress?: ProgressCallback | null,
  signal?: AbortSignal | null,
): Promise<number>

/** Rename stored members; resolves with the number renamed. */
export declare function renameEntries(
  archivePath: string,
  renames: RenameEntry[],
  password?: string | null,
  signal?: AbortSignal | null,
): Promise<number>

/** Set (or, with `null`/`undefined`, remove) the archive comment. */
export declare function setComment(
  archivePath: string,
  comment?: string | null,
  password?: string | null,
): Promise<void>

/**
 * Set (or, with `null`/`undefined`, remove) one member's file comment.
 *
 * RAR 1.5–4.x members only, like the CLI's `cf`.
 */
export declare function setMemberComment(
  archivePath: string,
  member: string,
  comment?: string | null,
  password?: string | null,
): Promise<void>

/** Add or replace the inline recovery record, protecting `percent` (0–100). */
export declare function setRecovery(
  archivePath: string,
  percent: number,
  password?: string | null,
): Promise<void>

/**
 * Lock the archive against further modification (like `rar k`).
 *
 * Refused on a multi-volume set: lock the first volume instead.
 */
export declare function lockArchive(
  archivePath: string,
  password?: string | null,
): Promise<void>

/**
 * Repair a damaged archive into `outputPath` using its recovery record.
 *
 * Resolves `true` when damage was found and repaired, `false` for an already
 * intact archive (in which case no output is written).
 */
export declare function repairArchive(
  inputPath: string,
  outputPath: string,
  onProgress?: ProgressCallback | null,
  signal?: AbortSignal | null,
): Promise<boolean>

/**
 * Rebuild a multi-volume set's missing volumes from its `.rev` recovery
 * volumes (like `rar rc`).
 *
 * `firstVolume` is `name.part1.rar`; resolves with the paths rebuilt, in
 * order, and an empty array when nothing was missing.
 */
export declare function rebuildMissingVolumes(
  firstVolume: string,
  onProgress?: ProgressCallback | null,
  signal?: AbortSignal | null,
): Promise<string[]>
